### ISSUE TITLE
Panda rebootstrap is failing on windows 7 64-bit

### ISSUE THREAD

**Issue by azawawi** [tadzik/panda#245]
This is happening with perl6 ```2015.10-220-g4988c70 built on MoarVM version 2015.10-61-g624d504```

```
d:\tools\panda>perl6 rebootstrap.pl
No need to rebootstrap, running normal bootstrap
==> Bootstrapping Panda
at 512: can't parse objects starting in
 yet
  in sub parse-thing at D:\tools\panda\ext\JSON__Fast\lib\JSON\Fast.pm:272
  in sub parse-array at D:\tools\panda\ext\JSON__Fast\lib\JSON\Fast.pm:216
  in sub parse-thing at D:\tools\panda\ext\JSON__Fast\lib\JSON\Fast.pm:245
  in sub parse-obj at D:\tools\panda\ext\JSON__Fast\lib\JSON\Fast.pm:167
  in sub from-json at D:\tools\panda\ext\JSON__Fast\lib\JSON\Fast.pm:291
  in method project-from-local at D:\tools\panda\lib\Panda.pm:63
  in method resolve at D:\tools\panda\lib\Panda.pm:187
  in sub MAIN at bin/panda:18
  in block <unit> at bin/panda:145

==> Please make sure that C:\rakudo/share/perl6/site/bin is in your PATH
```

**Comment by azawawi** [comment]
After debugging the problem of embedded `JSON::Fast`, it looks that `$initial` has the value `\r\n`.

**Comment by timo** [comment]
ohai, since i'm the author of JSON::Fast, here's my thoughts:

nom-ws ought to have skipped over the '\r\n' for us. it uses nqp::ordat and since '\r\n' is a synthetic here (proven by the fact that substr with a length of 1 gave us that) the ord of that should have been the ord of the "base character", which for \r\n is \n, i believe. could you give me the result of nqp::ordat($initial, 0)? nom-ws also checks for 13, which is \r, so ... i'm pretty much stumped.

**Comment by azawawi** [comment]
@timo I appreciate the speed of ```JSON::Fast``` and your excellent work on it. 

The fact is **panda is not working on windows for a while** and Christmas is around the corner. ```zef``` works but not for all packages that ```panda``` installs. We need to focus on more important tasks to make Perl 6 windows development easier and more stable.

Can we make ```JSON::Tiny``` a default option and if ```JSON::Fast``` is available, ```panda``` can use it or make it a ```--fast``` option until it is stable enough?

**Comment by timo** [comment]
We've found out that this is a bug in the JIT's implementation of nqp::ordfirst and nqp::ordat, where getting a synthetic doesn't properly cause the synthetic info to be grabbed. brrt is on the case. you'll find that MVM_JIT_DISABLE in the environment will fix this. i'm closing this, since it isn't really a panda bug anyway :)

**Comment by azawawi** [comment]
Cool. It is now working on windows! :+1: 

Thanks.
