### ISSUE TITLE
panda CLI inconsistent/confusing behaviour

### ISSUE THREAD

**Issue by vytas-dauksa** [tadzik/panda#256]
These doesn't work
* panda install Linenoise --force # ignores --force
* panda install --force Linenoise # warns --force

Following actually works:
* panda --force install Linenoise

though documentation sort of implies for me that --force should be after
```
    install        Installs the modules listed on the command line, and their
                   dependencies.
        --force      Install even if the same version of the module is already installed
```

**Comment by zoffixznet** [comment]
FWIW, the documentation does list the usage as `Usage:
    panda [options] <action>`

`install` is an action, so it should go last.

**Comment by stmuk** [comment]
I think adding a couple of examples at the top would help greatly

maybe 

panda --force install Foo::Bar

and

panda --installed list

I will submit a PR unless someone has a better idea?

**Comment by zoffixznet** [comment]
:+1:

**Comment by pdl** [comment]
Yes, please. Explicitly calling out that the options must precede the action would be good - I think 'try the thing that failed and add another option to the end' aka `up space dash dash force` is a common use case. Long term it would be nice to support all of the permutations unless there's a good reason not to.

**Comment by tadzik** [comment]
A reason not to is that I really didn't want to add a layer on top of what MAIN does in Perl 6: and the way it does, is that named arguments *have* to come first. I'm not very happy about it, and there used to be hacks in panda that enabled the "usual" behaviour, but I removed them over time partly because they were crap, and partly because I hoped attention may be brought to the big issue :)
