### ISSUE TITLE
Failed to stat file: no such file or directory

### ISSUE THREAD

**Issue by ohmycloud** [tadzik/panda#331]
I deleted all the files in the `C:\rakudo\share\perl6\site\sources` directory, when i try `panda install xxx`, it just said that:

`Could not open C:\rakudo\share\perl6\site\resources\1C71F7B377C6F2C6C4707E3C25016AA25A2926B1. Failed to stat file: no such file or directory`

It seems that my panda has broken.  Is there any way to fix this probrem, I don't want to re-install it.

**Comment by zoffixznet** [comment]
> I deleted all the files

Well, there's your problem! :joy_cat:  

Unfortunately, the easiest way to ensure you restore your system correctly is to re-install. You've basically taken a sledge hammer to a car and are asking to make it brand new again. Sure, there's probably a way to putty it over and respray, but it'll never have that brand new car smell again :smile_cat: 

In the future, would you please use one of our help channels? We have [#perl6 on Freenode IRC](https://webchat.freenode.net/?channels=#perl6), [#perl6 subreddit](https://www.reddit.com/r/perl6/), [Perl 6 Facebook page](https://www.facebook.com/groups/1595443877388632/). Github Issues are typically used to report problems with software, rather than to solicit help.
Thanks!

**Comment by ohmycloud** [comment]
thanks very much, I re-installed the whole rakudo-star. The [webchart]( https://webchat.freenode.net/?channels=#perl6) is awesome.
